### ISSUE TITLE
[BUG]: job qgis-installation-finder not working correctly

### ISSUE THREAD

**Issue by NROLLANDGrandlyon** [qgis-deployment/qgis-deployment-toolbelt-cli#505]
### Is there an existing issue or a documentation page for this?

- [X] I have searched the existing issues and within documentation

### Which version of the app are you using?

0.34.2

### Operating System

Windows 10+*

### Packaging mode

Stand-alone executable (.i.e qdt.exe)

### Description of the bug

J'ai essayé dans 2 cas avec 2 installations de QGIS sur le poste.

#### 1er cas

QGIS dans `Program File(x86)/QGIS 3.34.5/bin` et une autre version 3.34 dans `Program Files/QGIS3/bin`

Résultat :

```python
2024-05-02 15:00:03||WARNING||job_qgis_installation_finder||run||90||No QGIS installation found
2024-05-02 15:00:03||DEBUG||job_qgis_installation_finder||run||93||Job qgis-installation-finder ran successfully.
```

#### 2eme cas

QGIS dans `Program Files/QGIS 3.28.15/bin` et une autre version 3.34 dans `Program Files/QGIS3/bin`.

Résultat :

```python
2024-05-14 16:01:59||DEBUG||job_qgis_installation_finder||get_installed_qgis_path||132||Found installed QGIS : 
{'3.28.15': 'C:\\Program Files\\QGIS 3.28.15\\bin\\qgis-ltr-bin.exe'}
2024-05-14 16:01:59||INFO||job_qgis_installation_finder||get_installed_qgis_path||153||QGIS version(s) 
[3.34,3.28,3.22,3.18] not found. Using most recent found version 3.28.15 : C:\Program Files\QGIS 
3.28.15\bin\qgis-ltr-bin.exe
2024-05-14 16:01:59||DEBUG||job_qgis_installation_finder||run||93||Job qgis-installation-finder ran successfully.
```

Alors que la 3.34 est installée et que dans le job l'ordre est défini comme suit :

```yml
- name: Find installed QGIS
    uses: qgis-installation-finder
    with:
        version_priority:
        - "3.34"
        - "3.28"
        - "3.22"
        - "3.16"
```

### Relevant log output

```python
2024-05-02 15:00:03||INFO||journalizer||headers||118||========== QGIS Deployment Toolbelt - 0.34.2 ==========
2024-05-02 15:00:03||DEBUG||journalizer||headers||119||Operating System: Windows-10-10.0.19045
2024-05-02 15:00:03||DEBUG||journalizer||headers||124||Architecture: 64bit
```

### Comment

Donc ne semble trouver que les installations "standards" durant lesquelles on n'a pas modifié le chemin proposé par défaut par l'installateur.

**Comment by jmkerloch** [comment]
Je vais regarder ça.

@NROLLANDGrandlyon J'ai une idée du problème et j'aurais besoin de ces informations sur ton poste

Soit via powershell

```ps
$Env:PROGRAMFILES
```

Soit via l'invite de commande

```bat
echo %PROGRAMFILES%
```

**Comment by jmkerloch** [comment]
@NROLLANDGrandlyon Pour l'installation sur les chemins suivants:

- `Program File(x86)/QGIS 3.34.5/bin`
- `Program Files/QGIS3/bin`

Tu avais défini manuellement les chemins d'installation ?

**Comment by NROLLANDGrandlyon** [comment]
echo %PROGRAMFILES% donne C:\Program Files
L'installation dans Program File(x86)/QGIS 3.34.5/bin est une erreur SCCM. Ce n'est bien sûr pas la cible mais j'avais noté que QDT ne l'avait pas trouvé.
L'installation dans Program Files/QGIS3/bin est bien défini manuellement et c'est la cible pour tous les postes du Grand Lyon

**Comment by jmkerloch** [comment]
@NROLLANDGrandlyon 

Pour l'instant QDT ne peut trouver que les versions de QGIS installés avec les options _par défaut_. 
On va donc trouver uniquement les versions qui sont disponibles dans:

- la variable d'environnement `%PROGRAMFILES%` (chemin d'installation par défaut avec l'installeur QGIS)
- la variable d'environnement `%QDT_OSGEO4W_INSTALL_DIR%' (valeur par défaut `C:\\OSGeo4W` qui correspond au chemin par défaut pour l'installation OSGEO4W)

Un moyen de contournement pour le Grand Lyon serait éventuellement de passer par la variable d'environnement `QDT_OSGEO4W_INSTALL_DIR` qui devrait être définie sur `C:/Program Files/QGIS3/`

**Comment by NROLLANDGrandlyon** [comment]
OK. Je testerai cette façon de faire. De toute façon ce job est pour l'instant "optionnel" pour nous
Merci

**Comment by NROLLANDGrandlyon** [comment]
D'ailleurs puis-je définir cette variable d'environnement QDT_OSGEO4W_INSTALL_DIR dans le scénario ? ou faut-il le faire dans le système ?

**Comment by jmkerloch** [comment]
Je pense qu'on doit pouvoir la définir dans le scénario mais je t'avoue ne pas avoir encore testé complètement ce type d'option.

**Comment by Guts** [comment]
> D'ailleurs puis-je définir cette variable d'environnement QDT_OSGEO4W_INSTALL_DIR dans le scénario ? ou faut-il le faire dans le système ?

Tu as 2 façons de le faire :

- soit tu le mets dans les settings du scénario :

  ```yml
  [...]
  settings:
    OSGEO4W_INSTALL_DIR: chemin
  [...]
  ```  

- soit tu utilises le job [Environment Variables manager](https://guts.github.io/qgis-deployment-cli/jobs/environment_variables.html) **avant** le QGIS Finder :

  ```yml
  [...]
  ```yml
  [...]
  - name: Set environment variables
    uses: manage-env-vars
    with:
      - name: QDT_OSGEO4W_INSTALL_DIR
        action: "add"
        scope: "user"
        value: "\\chemin"
        value_type: path
  [...]
  ```  


Mais cela reste du contournement. Il faut voir si on ne devrait pas ajouter une option au job QGIS Finder pour pouvoir lui passer des chemins où chercher.

**Comment by jmkerloch** [comment]
Oui c'est clairement un coutournement. Il faut voir plus global. La liste de chemin de recherche me parait être une bonne idée.

**Comment by NROLLANDGrandlyon** [comment]
Il y  le chemin dans :

Ordinateur\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\Folders
Nom: C:\Program Files\QGIS3\
Valeur: 1


Ordinateur\HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\Shell\MuiCache\
Nom : C:\Program Files\QGIS3\bin\qgis-ltr-bin.exe.FriendlyAppName
Valeur : qgis-ltr-bin.exe

Dans 
Ordinateur\HKEY_CLASSES_ROOT\QGIS Project\Shell\open\command
Nom : (par défaut)
Valeur : "C:\PROGRA~1\QGIS3\bin\qgis-ltr.bat" "%1"

Je ne sais pas si c'est fiable mais généralement quand on veut une info Windows on la trouve dans le registre.
Bon après, dans le scénario il y avait 
QGIS_EXE_PATH:
      windows: "%PROGRAMFILES%/QGIS3/bin/qgis-ltr-bin.exe"

Ce qui revient à ajouter un chemin de recherche ?

**Comment by jmkerloch** [comment]
> Il y le chemin dans :
> 
> Ordinateur\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\Folders Nom: C:\Program Files\QGIS3 Valeur: 1
> 
> Ordinateur\HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\Shell\MuiCache Nom : C:\Program Files\QGIS3\bin\qgis-ltr-bin.exe.FriendlyAppName Valeur : qgis-ltr-bin.exe
> 
> Dans Ordinateur\HKEY_CLASSES_ROOT\QGIS Project\Shell\open\command Nom : (par défaut) Valeur : "C:\PROGRA~1\QGIS3\bin\qgis-ltr.bat" "%1"
> 
> Je ne sais pas si c'est fiable mais généralement quand on veut une info Windows on la trouve dans le registre. Bon après, dans le scénario il y avait QGIS_EXE_PATH: windows: "%PROGRAMFILES%/QGIS3/bin/qgis-ltr-bin.exe"
> 
> Ce qui revient à ajouter un chemin de recherche ?

Il faudrait regarder les logs mais en théorie si la valeur définie dans `QDT_QGIS_EXE_PATH` est valide on s'en sert.

Ma relecture du code montre qu'on ne va pas utiliser les variables d'environnement définie dans `QDT_QGIS_EXE_PATH`.

Donc on regarde dans  `PROGRAMFILES%/QGIS3/bin/qgis-ltr-bin.exe` au lieu d'aller dans `C:\Program Files\QGIS3\bin\qgis-ltr-bin.exe`.

==> il y a donc un bug sur l'utilisation de `QDT_QGIS_EXE_PATH` et le job `qgis-installation-finder`

**Comment by Guts** [comment]
Farfouiller dans la base de registre est une bonne piste à suivre. Le module est standard dans Python et on l'utilise déjà pour la gestion des variables d'environnement.

**Comment by NROLLANDGrandlyon** [comment]
En tout cas j'ai essayé avec le job Set env variable et ça fonctionne, la version est trouvée.
2024-05-15 11:20:55||DEBUG||job_qgis_installation_finder||get_installed_qgis_path||132||Found installed QGIS : 
{'3.34.5': 'C:\\Program Files\\QGIS3\\bin\\qgis-ltr-bin.exe'}

**Comment by NROLLANDGrandlyon** [comment]
Peut être que vos collègues qui "fabriquent" l'installeur pour Windows savent s'ils posent une donnée intéressante (fiable) dans la base de registre ?

**Comment by Guts** [comment]
J'ai documenté l'évolution ici : https://github.com/Guts/qgis-deployment-cli/issues/523
