### ISSUE TITLE
[BUG]: Running QDT.exe always pops a command windows

### ISSUE THREAD

**Issue by Guts** [qgis-deployment/qgis-deployment-toolbelt-cli#522]
### Is there an existing issue or a documentation page for this?

- [X] I have searched the existing issues and within documentation

### Which version of the app are you using?

0.34.5

### Operating System

Windows 10+*

### Packaging mode

Stand-alone executable (.i.e qdt.exe)

### Description of the bug

Expected behavior: no windows displayed when run as executable.

### Steps to reproduce

1. Download the QDT stand-alone executable
2. Open a terminal
3. Run it

A small command windows shows up.

### Comment

Spotted by Stéphane (https://github.com/lpoaura/)

**Comment by nicogodet** [comment]
I can't reproduce on 0.36.1

**Comment by Guts** [comment]
@sboitel any news about this?

**Comment by sboitel** [comment]
@Guts I confirm it was solved in previous version, thanks
